"""add attachments to chat messages

Revision ID: 662415373662
Revises: 4081c7f4ee63
Create Date: 2026-07-06 13:48:12.924118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662415373662'
down_revision: Union[str, Sequence[str], None] = '4081c7f4ee63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('attachments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'attachments')
    # ### end Alembic commands ###
